### ISSUE TITLE
Adjustments for 16-bit bytes (TI DSP)

### ISSUE THREAD

**Issue by altendky** [veorq/SipHash#16]
I am planning to use SipHash in a TI DSP with 16-bit bytes.  I tend to think achieving such compatibility will be sufficiently detrimental to the existing code that it would justify separate files if there is even interest in having it in this repo.  Maybe I'm lucky and I'm wrong about that. 
 Anyways, mostly just a heads up that I'm interested in and will be working on such a thing.  If there's any interest or knowledge of existing solutions I'd be happy to hear about it.  I'll share when I have something working.

**Comment by altendky** [comment]
It may be that I have a bad expectation for this code.  I personally try to avoid copy/paste usage and actually just refer to the original library (obviously including offering up various levels of 'improvements').  Anyways, other than the noise of mixing #18/#19 into this you can now see what it involves.

Perhaps as an alternative we could make the byte-size specific code 'pluggable'.  `#define`s and `#ifndef` in in this code base, or actual functions.  Then this code would only have to allow replacement of these things without actually having alternatives (big-endian, 16-bit bytes, etc) in this actual code base.

Or, maybe I need to walk away and make another copy/paste/modify.  :]

**Comment by altendky** [comment]
Now that there are 2 direct PR's for this and a related prep PR perhaps the general discussion should move here (ping @chrisnc).  Certainly either way can work and changes are required for anything to work (unless I have missed something).  I think the core question is whether the interface should be 'byte arrays' or '0-255 valued arrays'.

**Comment by chrisnc** [comment]
@altendky Thanks, #22 looks pretty good. Here's a simple question that I think would rule out the alternative of computing over 16-bit value sequences: how would a device with 16-bit bytes compute the hash of an odd-length octet sequence sent from another device with 8-bit bytes? If you define the interface as in #18 and #20 I don't think this is possible. This seems like a pretty reasonable use case: message integrity over, say, a UART link or something. The TI DSP's have support for several communication peripherals whose default or only mode of operation is octet-oriented. As I referenced in my other comment, the TI libc's I/O support is also octet oriented.

**Comment by altendky** [comment]
Good point and I agree odd numbers of octets should be supported and aren't presently in #20.  You could specify the input length to be an octet count regardless of octets per byte though.

Honestly though for my present use case this doesn't matter.  I'm hashing maybe 24 octets so 100% overhead is ok.  I'm just not convinced this is always a preferred choice.  I suppose supporting multiple calls passing smaller blocks of data would relate to making this cost more reasonable.
