### ISSUE TITLE
Alternative 128bit mode.

### ISSUE THREAD

**Issue by funny-falcon** [veorq/SipHash#28]
Excuse me for disturbing you.

I suggest alternative 128bit mode. Instead of producing second 64bit value after additional rounds, why not produce them at once, but xored with the key, ie use result whitening.
```c
    if (outlen == 16)
        v2 ^= 0xee;
    else
        v2 ^= 0xff;

    TRACE;
    for (i = 0; i < dROUNDS; ++i)
        SIPROUND;

    if (outlen == 8) {
        b = v0 ^ v1 ^ v2 ^ v3;
        U64TO8_LE(out, b);
    } else {
        b = v1 ^ k0;
        U64TO8_LE(out, b);
        b = v3 ^ k1;
        U64TO8_LE(out+8, b);
    }
```
(I skip xoring with v0 and v2 as it were found unnecessary earlier.)

Certainly, minimal recommended finalization rounds could be increased to 5.
In other worlds, minimum version will be called SipHash128-2-5.

Probably, before final xor k0 and k1 could be slightly modified. But simple `k0 += k1; k1 += k0` doesn't look to be good, because similar addition is in first operations of first round.
Probably `k0 += ROTL(k1, 7); k1 += ROTL(k0, 7);` will be good enough.

**Comment by veorq** [comment]
We will stick to the current version.
