### ISSUE TITLE
Document the claimed security of the experimental 128-bit version

### ISSUE THREAD

**Issue by drbo** [veorq/SipHash#3]
As I understand it, the 64-bit production version of SipHash is claimed to be as resistant as any other 64-bit MAC/PRF to attacks.  Is the security claim for the 128-bit version that it is as resistant as any other 128-bit PRF?

(In case anyone is wondering:  A big reason for wanting a 128-bit version is to use as a MAC for ciphers that does not require a nonce.  For instance, using SipHash-128 to generate both a MAC and part of the nonce for XSalsa20 or XChaCha20 encryption gives &ndash; presto! &ndash; instant nonce-misuse-resistant authenticated encryption with associated data.  Assuming, of course, that SipHash-128 is in fact secure.)

**Comment by veorq** [comment]
Thanks, added in c03e6bbf6613243bc30788912ad4afbc0b992d47
