### ISSUE TITLE
Add an interface header

### ISSUE THREAD

**Issue by tawmoto** [veorq/SipHash#31]
Hi, it would be great to add an interface header so one can build this lib as a static lib and have the original header there.
The header should contain the hash function declaration.

Thanks

**Comment by veorq** [comment]
Looks good? https://github.com/veorq/SipHash/pull/32

**Comment by tawmoto** [comment]
Hi, thanks for the PR, it needs a bit of change.

So basically in the interface you should put only what is necessary otherwise you will bloat the caller, so basically:
- add only the includes that you need, the rest keep them in the .c file
- move the `#defines` also in the .c file. The caller does not need to know anything about `U32TO8_LE` or `SIPROUND`

The interface should be as clean as possible, only the function definition and the mandatory includes, the rest should be in the .c
cheers!

**Comment by veorq** [comment]
Thanks! better now? https://github.com/veorq/SipHash/pull/32/commits/7786f93448a4191d0413b7e160da420ba1792af1

**Comment by tawmoto** [comment]
A lot better! Not sure you need `string.h`, you have no string in header, for size_t you can use a lighter include, like <stddef.h>
Thanks
