### ISSUE TITLE
Missing usage example from README.md

### ISSUE THREAD

**Issue by etc0de** [veorq/SipHash#9]
Can you provide a simple usage example in the README.md files to make it easier to get started with the reference implementation for people not deeply familiar with hashing?

A good example would be e.g. how to hash an arbitrary C string to a 64bit-length value, maybe also with a given global random seed if such a thing is supported.

Edit: is `k` the global random seed by any chance, of size 128bit? I have to guess a bit from the source code, it would be nice if there could be a short info on the parameters in the README.md for newcomers like me (or alternatively inside siphash.c itself as a doc comment).

**Comment by veorq** [comment]
README is being updated.
